### ISSUE TITLE
Permission issue with /versions

### ISSUE THREAD

**Issue by jadengore** [fisherman/fin#10]
On Fin's first install, things seem to work fine when I run the `fin` command. However, if I close `fish` and open again, I get this error when running `fin`:

```
mkdir: /versions: Permission denied
mkdir: /versions: Permission denied
fin: I couldn't create the fin configuration: 
```

**Comment by jadengore** [comment]
Followup: Seems like [this file](https://github.com/fisherman/fin/blob/master/conf.d/fin.fish) is not being sourced properly.

**Comment by bucaran** [comment]
Good call. I'll update the docs to make this point clear. Thanks @jadengore.!

**Comment by bucaran** [comment]
@jadengore 

Added support to self load conf.d when calling `fin` here: a917a6202347e3faec2c6ce23b19480a94e159b4

And a note to the README wrt to the fish 2.2.0 ~ 2.3.0 issue:
1e3f3945eaaf7ddbe8b5a2c72f2b73154758593e
