### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by FabioAntunes** [fisherman/fin#13]
I haven't tested Fin properly since I don't have time to play around with node versions as I'm afraid of breaking anything.

I'm trying to migrate from omf to fisherman, https://github.com/fisherman/fisherman/issues/223 but one thing that kept me from moving on was the fact that I needed my node versions installed.

I noticed that you have a function for npm and node, so I decided to do a little experiment.

I had already nvm installed, so I installed **fisherman**, installed **bass** created a **nvm** function inside the functions folder:
```bash
function nvm
  bass source ~/.nvm/nvm.sh --no-use ';' nvm $argv
end
```

Problem, node and npm are not available as noted here https://github.com/edc/bass/issues/28

Adding this line: 
```bash
bass source ~/.nvm/nvm.sh >/dev/null ^&1
```
to config.fish works, but makes the loading of the terminal 1/2 seconds slower

Then I installed fin, removed the previous line from the config.fish and without doing nothing I noticed that npm and node where already working.
I decided to remove fin and try a new thing, I noticed that you have created a function for npm and node, so what I did was "stealing" your functions, so on my functions folder now I have 4 functions:

**nvm.fish (same as above)**
```bash
function nvm
  bass source ~/.nvm/nvm.sh --no-use ';' nvm $argv
end
```
**npm.fish**
```bash
function npm -d "javascript package manager"
    __fin_run_bin_as "npm" $argv
end
```
**node.fish**
```bash
function node -d "Server-side JavaScript runtime"
    __fin_run_bin_as "node" $argv
end
```

**__fin_run_bin_as.fish (I was to lay to change the name):**
```bash
function __fin_run_bin_as -a name
    set -e argv[1]

    # Removed this
    #set -l local_versions (__fin_version_local)

    set -l current_version
    set -l finrc_version

    if test -s .finrc
        if test -s "$fin_config/version"
            read current_version < "$fin_config/version"
        end

        read finrc_version < .finrc

        if not fin "$finrc_version"
            return 1
        end

        read finrc_version < "$fin_config/version"
    end

    set -lx PATH $PATH
    set -l bin "$fin_config/bin"

    if test -s "$bin/node"
        set PATH "$bin" $PATH
    end

    if test "$name" = "node"
        command node $argv

    else if test "$name" = "npm"
        command npm $argv

    else
        echo "fin: Error: I don't know what is '$name'." > /dev/stderr
    end
    
    # Removed also this
    #if test ! -z "$finrc_version"
    #    if not contains -- "$finrc_version" $local_versions
    #        fin rm "$finrc_version"
    #    end

    #   if test ! -z "$current_version"
    #       fin "$current_version"
    #   end
    #end
end
```

Notice that on this last one I removed all the stuff related to the function **__fin_version_local**

So far everything is working fine, would you consider creating a fisherman plugin for nvm with this functions, so people that already have nvm installed, specially people coming from the omf world like me, can keep on using their nvm stuff?

**Comment by bucaran** [comment]
Sweet! I would love too, but maintaining two projects it's not going to do it for me :)

What we can do is, invite you to the fisherman org and let you take the lead on that. 

If that sounds okay, just say the magic words and I'll send you an invite.

**Comment by FabioAntunes** [comment]
This is embarrassing, but all that stuff that I said is false, things were working because somehow I managed to test all my changes on terminals which had nvm, npm and node on session.

None of that stuff is  true and it doesn't work.

But I did manage to solve my problem creating some functions that check if node or npm exists if not just run `nvm use` or `nvm use default`

### Files:
**node.fish**
```bash
function node -d "Server-side JavaScript runtime"
  __nvm_plugin_run "node" $argv
end
```

**npm.fish**
```bash
function npm -d "node package manager"
  __nvm_plugin_run "npm" $argv
end
```
**nvm.fish**
```bash
function nvm
  bass source ~/.nvm/nvm.sh --no-use ';' nvm $argv
end
```

**__nvm_plugin_can_run.fish**
```bash
function __nvm_plugin_can_run
  if type -P $argv[1] > /dev/null 2>&1
      return
  else
    return 1
  end
end
```


**__nvm_plugin_run.fish**
```bash
function __nvm_plugin_run
  set count (count $argv)

  echo $argv
  if test "$count" -le 0
    echo 'No params'
    return 1
  else  if begin test $argv[1] != "node";  and  test $argv[1] != "npm"; end
    echo 'first argument must be node or npm'
    return 1
  end

  function run_command
    set count (count $argv)

    if test "$count" -ge 2
      set args $argv[2..-1]
    else
      set args ""
    end

    switch $argv[1]
    case npm
      command npm $args
    case node
      command node $args
    end
  end

  function run_default
    nvm use default
    if __nvm_plugin_can_run $argv[1]
      run_command $argv
    end
  end

  if not __nvm_plugin_can_run $argv[1]
    if test -f .nvmrc; and nvm use > /dev/null 2>&1

      if __nvm_plugin_can_run $argv[1]
        run_command $argv
      else
        run_default $argv
      end
    else
      run_default $argv
    end
  else
    run_command $argv
  end
end

```

**Comment by bucaran** [comment]
@FabioAntunes Well, if you are happy with that and it works for you, cool, why not :)

**Comment by FabioAntunes** [comment]
@bucaran one thing though I was looking at the omf/nvm plugin and they have completions for nvm I tried to copy some of them, but I was unable to make them work, if I have a `completions/` folder inside the  `~/.config/fish/functions/`  will fish look at that folder? I think thats the only thing that's missing to create a really nice plugin for fisherman which doesn't increase terminal loading time by sourcing the nvm everytime, since we only source when we try to use any npm or node command

**Comment by bucaran** [comment]
@FabioAntunes ~~nvm~~ _fin_ does not work like that! :) We shim `node` and `npm` so while we do setup the PATH on startup, this probably only accounts for like 5~10ms.

**Comment by FabioAntunes** [comment]
@bucaran I know my idea was to create some plugin to use nvm, so people who are already using nvm could keep on using it with fisherman

**Comment by bucaran** [comment]
@FabioAntunes Ah, right.

In that case, yes, sourcing `nvm` on startup would not be a sane thing to do. WRT to completions, yes, if your completions are properly written, create a new directory `completions` in the root level of your nvm plugin and put them there.

**Comment by bucaran** [comment]
@FabioAntunes I have created a repo and added you as the maintainer. Can you add your work there?
