### ISSUE TITLE
add global packages to the PATH

### ISSUE THREAD

**Issue by bucaran** [fisherman/fin#15]
Comment by @DanielRamosAcosta
* https://github.com/fisherman/fin/issues/14#issuecomment-215059839

Related #14

**Comment by bucaran** [comment]
Okay, the problem is how we are copying files from the cache into the configuration. I was worried this was going to be impossible due to how I was shimming `node` and `npm`, but as it turns out, it's quite doable.

I'll push my changes and release as fin@1.2.0.

**Comment by DanielRamosAcosta** [comment]
Just upgraded fin and I still can't use the global packages... Don't know why.
![global](https://cloud.githubusercontent.com/assets/11427028/14864720/0fb659b6-0cb3-11e6-9037-b1fadbc3031e.png)

**Comment by bucaran** [comment]
@DanielRamosAcosta

**Comment by DanielRamosAcosta** [comment]
Sorry, but yesterday I had an horrible headache... I tried `fish --version` and look at this:
![fish-version](https://cloud.githubusercontent.com/assets/11427028/14879725/cf2cee62-0d22-11e6-9414-2e269beeeec3.png)

Did I installed `fish` wrong or something?

Here are the steps I did:

1. Go to [fish repo](https://github.com/fish-shell/fish-shell/releases) and copy 2.3b1 commit sha1 (`43535cf5a5a295f7a34adede28afd90dcd9aa739`)
2. Clone repo and checkout that commit
3. `autoconf`, `./configure`, `make`, `sudo make install`

In that moment I remember doing `fish --version` and get `2.3b1`, but now no... I don't know what is causing this.

Here is my `$PATH` also:

```fish
~> echo $PATH
/home/daniel/.rvm/gems/ruby-2.3.0/bin /home/daniel/.rvm/gems/ruby-2.3.0@global/bin /home/daniel/.rvm/rubies/ruby-2.3.0/bin /home/daniel/.rvm/bin /home/daniel/.config/fin/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin
```

**Comment by bucaran** [comment]
```ls -a /home/daniel/.config/fin/bin```

**Comment by DanielRamosAcosta** [comment]
Here it is:
![fin-update-bower](https://cloud.githubusercontent.com/assets/11427028/14880173/56937414-0d25-11e6-9008-8124d89047c3.png)

Seems to be fixed! Thanks a lot @bucaran :smile:

**Comment by bucaran** [comment]
Great, thanks to you @DanielRamosAcosta for reporting it.
