### ISSUE TITLE
Fuzzy-matching of latest major version numbers is not supported

### ISSUE THREAD

**Issue by derekcecillewis** [fisherman/fin#16]
Please add support for fuzzy-matching of latest major version numbers such as `latest-v6.x` as seen here: [https://nodejs.org/dist/](https://nodejs.org/dist/). Another idea would be to automatically select the latest version if minor or patch version numbers are omitted, such that running `fin latest 6` would match to `latest-v6.x`.

**Comment by bucaran** [comment]
Done.

+ [ x ] latest-vMAJOR.x _or_ latestMAJOR.x _or_ latestMAJOR
+ [ x ] MAJOR → MAJOR.latest_minor.latest_patch
+ [ x ] MAJOR.minor → MAJOR.minor.latest_patch
+ [ x ] MAJOR.minor.patch → exact match

For example

```
fin 4 # 4.4.4
```

```
fin 4.3 # v4.3.2
```


```
fin 6 # v6.1.0
```


```
fin latest0.12 # v0.12.13
```

etc.
