### ISSUE TITLE
nvm install seemingly broken

### ISSUE THREAD

**Issue by codingismy11to7** [fisherman/fin#167]
I'm not an expert so forgive me, my fish version is `3.3.1`, nvm version is `2.2.6`. On an intel mac.

I tried many different ways to install node `12.22.7`, and eventually ended up debugging `nvm install v12.22.7`. It seems like the line
```
string match --entire --regex -- (_nvm_version_match $v) <$nvm_data/.index | read v alias
```
changes the value of `$v` from `v12.22.7` to `v12.22.7 lts/erbium`. Then this value is used in the `$url` variable later on, ending up with a URL which doesn't exist.

**Comment by jorgebucaran** [comment]
Hmm, I am on an Intel mac and unable to reproduce it. 

`read v alias` will save the Node version and alias into their respective variables, e.g.:

```fish
echo a b | read v alias
printf "%s\n" $v $alias
```
```console
a
b
```

**Comment by codingismy11to7** [comment]
thanks for checking, must be something in my environment, somehow

**Comment by jorgebucaran** [comment]
Could you check if the code using `read` that I posted above produces the indicated output?

**Comment by codingismy11to7** [comment]
well I saw that both were definitely being added to `v`. this was on my work computer, I can check on Monday

**Comment by codingismy11to7** [comment]
```
user@machine /tmp> echo a b | read v alias
user@machine /tmp> echo $alias

user@machine /tmp> echo $v
a b
user@machine /tmp> printf "%s\n" $v $alias
a b

user@machine /tmp> 
```

actually right as I was pasting this I realized it was probably my `$IFS` variable, so I set it to `" "` and then got the expected output

**Comment by jorgebucaran** [comment]
Seems like we forgot to close here.
