### ISSUE TITLE
Collision with rvm

### ISSUE THREAD

**Issue by DanielRamosAcosta** [fisherman/fin#17]
I uninstalled fin, and I get my normal terminal startup:

![sinfin](https://cloud.githubusercontent.com/assets/11427028/14880969/d8d4efc6-0d29-11e6-8244-abf5c0a37176.png)

But after installing `fin`, `rvm` reports not to be the first in `$PATH`:

![withfin](https://cloud.githubusercontent.com/assets/11427028/14880975/de8aa190-0d29-11e6-88f5-cd2ce61bff43.png)

**Comment by bucaran** [comment]
@DanielRamosAcosta Thanks.

What would it be the correct course of action here?

**Comment by DanielRamosAcosta** [comment]
Yup, now there is no warning

**Comment by bucaran** [comment]
Good to close then? :)
