### ISSUE TITLE
Apple Silicon support for Node 14

### ISSUE THREAD

**Issue by snkedive** [fisherman/fin#171]
Apple Silicon support was backported to Node 14 as of [v14.17.0](https://github.com/nodejs/node/pull/38051). Therefore, nvm should use arm64 for this version as well when appropriate.

**Comment by ljharb** [comment]
https://nodejs.org/dist/v16.0.0/ includes "darwin-arm64" binaries; v14.17 doesn't: https://nodejs.org/dist/v14.17.6/

**Comment by snkedive** [comment]
> https://nodejs.org/dist/v16.0.0/ includes "darwin-arm64" binaries; v14.17 doesn't: https://nodejs.org/dist/v14.17.6/

Ah, I see. It appears to be supported, but binaries are not provided for versions <16. I assumed they were since Homebrew works with them, but it appears to get around this by compiling from source.

**Comment by ljharb** [comment]
Yes, the node folks seem to be telling me that `^14.17` can be *compiled* on non-rosetta M1, but only 16+ has prebuilt binaries.

**Comment by jorgebucaran** [comment]
Closing, since nvm.fish just do binaries, and we can't (unfortunately) do much here at this time.
