### ISSUE TITLE
'lts' not found

### ISSUE THREAD

**Issue by Jeroendevr** [fisherman/fin#175]
NVM version 0.39.1

when running `nvm install lts` my terminal responds with 
> Version 'lts' not found - try `nvm ls-remote` to browse available versions.

Using `nvm install v16` works correctly and installs v16.14.

**Comment by ljharb** [comment]
I think that version number is for nvm.sh, not for nvm.fish - and it’d be `nvm install --lts`

**Comment by Jeroendevr** [comment]
Thanks for the reply, I really thought I was using nvm fish. Ok I will go and configure my shell properly.
