### ISSUE TITLE
Problems with .nvmrc

### ISSUE THREAD

**Issue by benjick** [fisherman/fin#176]
Hello

I'm using `nvm, version 2.2.6` and it seems it can't pick up my `.nvmrc`. Not really sure what I should do. It works fine if I specify the version but I would prefer it to adhere to the rc file.

<img width="418" alt="Screenshot 2022-03-16 at 11 10 37" src="https://user-images.githubusercontent.com/430872/158566851-be2c1c00-f4ce-4cd9-a207-62584ca017cd.png">

**Comment by jorgebucaran** [comment]
@benjick Thanks. We read it but failed to print it. Should be good now. 

The other issue you are having is that nvm.fish wants you to nvm install the version first, then run `nvm use` to switch to it.

**Comment by jorgebucaran** [comment]
@benjick Thanks. We read it but failed to print it. Should be good now. 

The other issue you are having is that nvm.fish wants you to install the version first, then run `nvm use` to switch to it.

**Comment by benjick** [comment]
@jorgebucaran hey, thanks for the quick reply/commit 🙏 seeing another issue now though

`.nvmrc` is utf8 with CRLF

<img width="532" alt="Screenshot 2022-03-16 at 20 53 17" src="https://user-images.githubusercontent.com/430872/158678357-a01f533d-16c1-47d5-8cd6-d23fc619be55.png">

```
nvm -v
nvm, version 2.2.7
```

**Comment by jorgebucaran** [comment]
@benjick Perhaps a Fish issue? We just use `read v <$file` to read the version into a variable.

https://github.com/jorgebucaran/nvm.fish/blob/e4e603af527677dc954c5e6d1730bdf36f0e5ba1/functions/nvm.fish#L4 

Can you run the following and make sure you get the expected result?
```fish
echo 16 > .nvmrc
read v <.nvmrc 
echo $v
```

**Comment by benjick** [comment]
```
echo 16 > .nvmrc
read v <.nvmrc
echo $v
16
```

**Comment by jorgebucaran** [comment]
And what happens if you run `nvm install` or `nvm use` with that `.nvmrc`?

You can help me debug this by adding some logging after we read the version into `$v`. Are we picking up the version or not? As a Fish script, I don't usually have to worry about file encoding or control codes, so this intrigues me.
