### ISSUE TITLE
Make compatible with .nvmrc files?

### ISSUE THREAD

**Issue by elliottsj** [fisherman/fin#18]
For a Node.js project which has developers using both nvm and fin, it seems redundant to have both a `.nvmrc` and a `.finrc` file. Thoughts about making fin compatible with `.nvmrc` files?

The obvious issue is that fin's `lts` / `latest` aliases differ from nvm's `stable` / `unstable` / `node` / `iojs` aliases; I'd be ok with having fin fail silently if it finds an nvm-specific alias, I only ever put specific Node versions in `.nvmrc` files anyway.

<h1></h1>

**TODO**

+ [ ] Read .nvmrc files.
+ [ ] Read .node-version files.

**Comment by bucaran** [comment]
@elliottsj I would be okay with making `fin` more compatible with nvm. I'll add support to .nvmrc in the next release.

WRT to nvm aliases, we could support some or as you say, fail silently, since some of them exist just for historical reasons.

**Comment by jamesmoss** [comment]
Would it be possible to configure the name of the version file? At my work we use https://github.com/wbyoung/avn which uses a `.node-version` file rather than `.nvmrc`.

**Comment by bucaran** [comment]
@jamesmoss I think we could make fin support all three of them without much penalty checks. The check order would be .finrc > .nvmrc > .node-version.

**Comment by jamesmoss** [comment]
That would work for us.

**Comment by bucaran** [comment]
Perfect. I'll ping you as soon this is done.

**Comment by jadengore** [comment]
👍 to this

**Comment by bucaran** [comment]
fin now searches for any existing, non-empty, *.finrc*, *.nvmrc* or *.node-version* file to version switch, and in that order. If none is found, it uses the *currently selected* node version, .eg., `fin 6.0.0` if there is any available.
