### ISSUE TITLE
Issue installing packages behind proxy

### ISSUE THREAD

**Issue by yutsuo** [fisherman/fin#180]
OS Ubuntu 21.10
nvm fish version 2.2.7

Can't install npm packages behind a corporate proxy:

```sh
nvm install 17

Installing Node v17.8.0 latest
Fetching https://nodejs.org/dist/v17.8.0/node-v17.8.0-linux-x64.tar.gz
curl: (52) Empty reply from server                                      #       #      #     #               
nvm: Invalid mirror or host unavailable: "https://nodejs.org/dist/v17.8.0/node-v17.8.0-linux-x64.tar.gz"
```

curl is correctly configured to use proxy.

list-remote option works.

Thought it could be something to do with the proxy config, but then I changed to nvm in bash using same config and installation works normally.

**Comment by jorgebucaran** [comment]
What did you expect would happen exactly? What should we do?

**Comment by yutsuo** [comment]
In that case I expected nvm-fish to complete the installation of Node v17.8.0

Because bash nvm worked under the same conditions I'm curious about why nvm-fish behaved differently.

Didn't find an issue about it so I opened this one to make it known.

I will try to investigate the cause.

**Comment by jorgebucaran** [comment]
Closing as stale. No one else has reported this issue, and I see nothing actionable here for now. If you do find out what was causing trouble, do let us know @yutsuo! 🙏
