### ISSUE TITLE
.nvmrc not found - traversing the directory hierarchy 

### ISSUE THREAD

**Issue by franciscolourenco** [fisherman/fin#183]
`nvm use/install` works if `.nvmrc` is in the same directory, but not if it is in the parent directory

```
$ nvm use
nvm: Invalid version or missing ".nvmrc" file
$ fish --version
fish, version 3.4.1
$ nvm --version
nvm, version 2.2.7
```

Can you reproduce?

**Comment by jorgebucaran** [comment]
I can't reproduce this. Also using nvm.fish 2.2.7 and Fish 3.4.1. I added a test to show it works. 

This is where we attempt to read the closest .nvmrc by traversing the directory hierarchy until it is found.

https://github.com/jorgebucaran/nvm.fish/blob/71593b324a5ad02996c6715a19358869440d9930/functions/nvm.fish#L3-L5
