### ISSUE TITLE
nvm_default_version not working for setting default

### ISSUE THREAD

**Issue by metruzanca** [fisherman/fin#189]
_New to fish_

So I got `set --universal nvm_default_version 12` in my config.fish but it keeps loading LTS (which is the first version that I installed).

What am I doing wrong?

EDIT: vscode was caching something apparently?

**Comment by salmanhasni** [comment]
@metruzanca how did you resolve it ?

**Comment by metruzanca** [comment]
@salmanhasni In my case I had installed nvm.fish and just closed my vscode terminal and reopened it. Upon checking the environment variables, I noticed `echo $nvm_default_version` was not updating, so I thought vscode might be caching something. So I FULLY close all vscode instances (not just the integrated terminal) and then it just started working (and checking the env var, its now updated)

**Comment by evilPaprika** [comment]
Thank you so much, fully closing vscode and opening it again helped. I spend hours trying to make it work
