### ISSUE TITLE
VSCode debug "can't find Node.js binary"

### ISSUE THREAD

**Issue by SteveMelons** [fisherman/fin#191]
When trying to use the debug feature in VSCode, it throws an error saying that it cannot find the node binary.

![image](https://user-images.githubusercontent.com/44551583/177161750-db071f5a-fad8-4e69-89ae-17e3445652a7.png)

launch.json
```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceFolder}/src/app.ts",
      "outFiles": [
        "${workspaceFolder}/**/*.js"
      ]
    }
  ]
}
```

Is there any special configuration needed to get this to work?

**Comment by jorgebucaran** [comment]
Are you using nvm.fish in Windows? Does it work outside Code?

**Comment by SteveMelons** [comment]
I am using WSL2 with Ubuntu installed. I'm using the fish shell there and this plugin to manage the node versions. And everything works fine from the terminal, just not when using VSCode.

**Comment by jorgebucaran** [comment]
Your base OS is still Windows, correct? Who launches VSCode? What's in your PATH when VSCode starts?

Do you also happen to have a config.fish? Can you show me what's in it?

**Comment by jorgebucaran** [comment]
@SteveMelons Ping

**Comment by jorgebucaran** [comment]
Closing as stale.
