### ISSUE TITLE
`nvm alias`

### ISSUE THREAD

**Issue by lunaleaps** [fisherman/fin#200]
I'm trying to use `nvm alias` as I'm trying to debug why I'm getting an error like:

```
N/A: version "default" is not yet installed.
```

and I've seen [advice](https://stackoverflow.com/questions/71096289/react-native-fbreactnativespec-command-phasescriptexecution-failed-with-a-nonz) to run `nvm alias` and `nvm unalias`.

I don't see those as commands available for the fish port -- I'm wondering if there's an equivalent?

**Comment by jorgebucaran** [comment]
We don't have an nvm alias yet. Why do you need it?

**Comment by lunaleaps** [comment]
I was attempting to debug an issue with a React Native version that had an error:

```
N/A: version "default -> N/A" is not yet installed.

You need to run "nvm install default" to install it before using it.
Command PhaseScriptExecution failed with a nonzero exit code
```
And the [recommended solution](https://stackoverflow.com/a/72566345) was to use `nvm alias` to define a `default` version. I had tried setting `$nvm_default_version` but that didn't seem to work. 

I ended up switching to `fish-nvm` as I needed this. Just raising it up

**Comment by jorgebucaran** [comment]
How exactly $nvm_default_version didn't work?

**Comment by lunaleaps** [comment]
Well `nvm install default` didn't work as `default` isn't recognized. 
I mentioned `$nvm_default_version` to share my guess at getting this to work but I'm not sure that's the desired behavior. Since defining an alias of `default` is different than setting a default node version. 

I'll close this issue for now as it seems there isn't value in adding this `alias` command and I'm fine using another solution

**Comment by jorgebucaran** [comment]
Yeah, but that's not how `$nvm_default_version` works.
