### ISSUE TITLE
download url wrong when `nvm_arch=x64-musl`

### ISSUE THREAD

**Issue by everyx** [fisherman/fin#201]
We should use `https://unofficial-builds.nodejs.org/download/release/` for `x64-musl`, one workaround is set `nvm_mirror=https://unofficial-builds.nodejs.org/download/release/`, but I think it will be better dev experience if it can be handled in `nvm.fish`

**Comment by jorgebucaran** [comment]
I think that using `nvm_mirror` as you stated is an acceptable workaround for now, but we can always look into it if someone can send us a PR.

**Comment by jorgebucaran** [comment]
I had another look at this and I'm still torn. On one hand, I think this is exactly why we introduced $nvm_mirror. On the other hand, I agree that it would be a better developer experience to have this feature out of the box. For now, I'm going to keep this closed. However, I'm open to revisiting this in the future if things change or we hear from others.
