### ISSUE TITLE
lsr(list-remote), install give me error and list(ls) give me nothing

### ISSUE THREAD

**Issue by ClearPlume** [fisherman/fin#205]
Here is `nvm lsr` error:
![image](https://user-images.githubusercontent.com/18047536/227838118-6b91bb57-2bca-4f61-857d-a02a3701bd8a.png)

Here is `nvm install lts` error:
![image](https://user-images.githubusercontent.com/18047536/227838299-4c92bf49-81f4-4390-968a-e9f1ee0c50e2.png)
![image](https://user-images.githubusercontent.com/18047536/227838377-7edeaace-fbce-43a8-bed6-198e8d5496a5.png)
![image](https://user-images.githubusercontent.com/18047536/227838255-f757cb79-1a5d-4f98-b31d-d70089bc3aee.png)

Fortunately, although there was an error with `nvm install lts`, it was installed successfully and `node -v` is also working.

**Comment by jorgebucaran** [comment]
What version of Fish are you using?

**Comment by jorgebucaran** [comment]
@ClearPlume ☝️

**Comment by lucasportella** [comment]
I'm having this same issue. Just reinstalled it and the error persists. Version 2.2.11-1. Installed in Garuda Linux via AUR.

**Comment by jorgebucaran** [comment]
@lucasportella Fish 2.x is not supported. Please upgrade to the latest Fish.

**Comment by lucasportella** [comment]
@jorgebucaran, my bad, i meant Version 2.2.11-1 for nvm fish, my version of fish is 3.6.1-1

**Comment by jorgebucaran** [comment]
Did you install nvm.fish with Fisher?

**Comment by lucasportella** [comment]
No i didn't. But now I reinstalled nvm-fish with Fisher and it worked perfectly. Thanks.

**Comment by ClearPlume** [comment]
> What version of Fish are you using?

@jorgebucaran Sorry for the late reply! My fish version is 3.6.1, and here is my system info:
![图片](https://user-images.githubusercontent.com/18047536/229327896-8d84f0bc-7633-443c-b3b4-a1168d9ddee2.png)

**Comment by jorgebucaran** [comment]
Are you also using the latest Fisher and nvm.fish? Did you try reinstalling?

**Comment by ClearPlume** [comment]
> Did you install nvm.fish with Fisher?

I previously installed `fish-nvm` with `Pacman`(archlinuxcn) and `AUR`, After seeing your message, I installed `fisher` and used it to install `jorgebucaran/nvm.fish`. It works fine now... Thank you!

**Comment by ClearPlume** [comment]
> Are you also using the latest Fisher and nvm.fish? Did you try reinstalling?

Well, I just tried uninstalled `fish-nvm` installed by `Pacman` and then installed `jorgebucaran/nvm.fish` with `fisher`. Now it works fine.

**Comment by jorgebucaran** [comment]
Ah, now I get it! Sadly, I don't have control over those packages and can't figure out the issue. I'd be more than willing to help the authors fix it, but in the meantime, I'd suggest installing nvm with Fisher, which I actually maintain.
