### ISSUE TITLE
$nvm_default_version not working

### ISSUE THREAD

**Issue by akleiber** [fisherman/fin#213]
Hello there and thank you for the great implementation!

I tried to setup having node ready for every new session but I can not manage to make it work.

I set the the default version via `set --universal nvm_default_version` and the variable is there, but `nvm install` does not recognize the variable or version.

![Screenshot 2023-09-07 at 08 25 08](https://github.com/jorgebucaran/nvm.fish/assets/1506973/ee1aff0f-0b07-4c89-aaf8-3314f057c768)

```
nvm --version
nvm, version 2.2.13
```

Anything I am missing here?

**Comment by akleiber** [comment]
oh wow I am stupid... it will just work by opening a new session

**Comment by jorgebucaran** [comment]
No worries! 😄
