### ISSUE TITLE
nvm use on new tab terminal

### ISSUE THREAD

**Issue by Natchii59** [fisherman/fin#218]
I'm on Webstorm and when I open the terminal nvm doesn't use the node version of the project. In this one I have the .nvmrc file and I open a terminal with fish.
It would be nice if nvm detected the file when opening a terminal.
<img width="1440" alt="image" src="https://github.com/jorgebucaran/nvm.fish/assets/96394660/b76a0eab-ae5e-490c-a90f-37f61be0af15">

**Comment by jorgebucaran** [comment]
Did you see [jorgebucaran/nvm.fish#nvm_default_version](https://github.com/jorgebucaran/nvm.fish?tab=readme-ov-file#nvm_default_version)?

**Comment by jorgebucaran** [comment]
> It would be nice if nvm detected the file when opening a terminal.

Ah, I see you're interested in automatic version switching. Unfortunately, that is not a feature I plan to implement in nvm for reasons discussed in https://github.com/jorgebucaran/nvm.fish/pull/181. However, you can find an easy solution in https://github.com/jorgebucaran/nvm.fish/pull/186#issuecomment-1142412874.
