### ISSUE TITLE
NVM not automatically enabled

### ISSUE THREAD

**Issue by alper** [fisherman/fin#220]
I have the actual nvm installed and I thought this plugin would (similar to the pyenv fish plugin) enable some node version automatically. 

This is not the case? I need to add the command to fish.config myself?

**Comment by jorgebucaran** [comment]
https://github.com/jorgebucaran/nvm.fish?tab=readme-ov-file#nvm_default_version

**Comment by aweibell** [comment]
This seems to only provide `node` as an available command after running `nvm use` in any new terminal? Is there a recommended way to always have node available when you open a new terminal?

Thank you for all your efforts for a great terminal experience, BTW, @jorgebucaran :)

**Comment by jorgebucaran** [comment]
> Is there a recommended way to always have node available when you open a new terminal?

Yes. [nvm_default_version](https://github.com/jorgebucaran/nvm.fish?tab=readme-ov-file#nvm_default_version) exists for that purpose.
