### ISSUE TITLE
NVM install fails with `Invalid mirror or host unavailable` for some `~/.curlrc` files

### ISSUE THREAD

**Issue by bcspragu** [fisherman/fin#223]
The problem: `nvm install` was totally broken for me, showing an error like:

```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

This was a pretty maddening issue to debug (and ultimately entirely my fault) but the issue is here:

https://github.com/jorgebucaran/nvm.fish/blob/c69e5d1017b21bcfca8f42c93c7e89fff6141a8a/functions/nvm.fish#L116-L117

The problem is that if someone has a `~/.curlrc` file that contains something like `-w "\n"` (to make output more readable), it breaks `tar` because tar isn't expecting the newline. The solution is just to make the `curl` call `curl --disable`, so that it doesn't read the `.curlrc` file at all.

**Comment by jorgebucaran** [comment]
That sounds pretty straightforward. Send me a PR with the fix that worked for you so I can test it in my environment.

**Comment by bcspragu** [comment]
Sounds good, sent out https://github.com/jorgebucaran/nvm.fish/pull/224
