### ISSUE TITLE
Using nvm.fish from .envrc

### ISSUE THREAD

**Issue by oschrenk** [fisherman/fin#229]
This is not reporting a defect more of a curiosity I think , so feel free to ignore/close

I am looking for advice on how to run `nvm.fish` from an `.envrc` file loaded via `direnv`.

The `.envrc` file:

```
[ -s "$HOME/.config/fish/functions/nvm.fish" ] && fish -c "nvm list; nvm use v16.16.0";
```

But nvm seems to default to the system version. The output:
```
direnv: loading ~/Projects/acme/.envrc
     system
 ▶ v16.16.0 lts/gallium
Now using Node v22.8.0 (npm 10.8.2) /opt/homebrew/Cellar/node/22.8.0/bin/node
```

While `nvm list` does pick up the right version. The subsequent `nvm use` seems to ignore it. I am pretty sure this has to do with some shell shenanigans, as running `nvm use v16.16.0` directly works.

Interestingly enough, when using a wrong version:

```
[ -s "$HOME/.config/fish/functions/nvm.fish" ] && fish -c "nvm list; nvm use foooo";
```

will result in 

```
direnv: loading ~/Projects/acme/.envrc
     system
 ▶ v16.16.0 lts/gallium
nvm: Can't use Node "foooo", version must be installed first
```

so `nvm` does parse the version but for some reason doesn't use it in this context.

**Comment by oschrenk** [comment]
Ah. Using search term direnv showed me

https://github.com/jorgebucaran/nvm.fish/issues/131

It seems that nvm 2.x is not working with direnv

**Comment by oschrenk** [comment]
For that matter it also means i can't run it via https://taskfile.dev I think.

**Comment by jorgebucaran** [comment]
Hey! Late reply, sorry. Could you clarify what you expected to happen exactly? Just switch to 16.6.0 momentarily? Why were you trying to run nvm from the .envrc? It could be a bug in nvm.fish or direnv or neither, but I'm not really sure what you were aiming for.

**Comment by jorgebucaran** [comment]
Hey! Late reply, sorry. Could you clarify what you expected to happen exactly? Just switch to 16.16.0 momentarily? Why were you trying to run nvm from the .envrc? It could be a bug in nvm.fish or direnv or neither, but I'm not really sure what you were aiming for.

**Comment by oschrenk** [comment]
> Why were you trying to run nvm from the .envrc? 

That is the current setup at $WORK - I'm the only one using fish and thus can't use the "regular" nvm. 
The setup is

```
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh"
nvm use v16.16.0
```

With `nvm.fish` installed one might think above should work, but it doesn't because, nvm is just a fish function, so executing `direnv allow` will result in

```
./.envrc: nvm: command not found
```

Then I thought, what if I can trigger nvm (the fish version) from a shell. So I tried adding

```
[ -s "$HOME/.config/fish/functions/nvm.fish" ] && fish -c "nvm list; nvm use v16.16.0";
```

My expectations were that this would load node version 16 in the current directory. But it doesn't it defaults to the system version instead.

I believe this has something to do with 

https://github.com/jorgebucaran/nvm.fish/issues/131

So I don't think we can make it work. 

I hope this was a better explanation. I will still close the issue because I feel this can't be solved.

**Comment by jorgebucaran** [comment]
We're using direnv at $WORK as well, and I'm also the only one using Fish. Luckily, I haven't run into a setup where I need to embed shell junk into an .envrc. I would have assumed that running fish -c "nvm use ..." would set the specified Node version within that subshell, not for the entire directory. Is that what you were expecting?

**Comment by oschrenk** [comment]
yes.  I expected to set for the current directory. But of course it only sets it only for the subshell.

**Comment by jorgebucaran** [comment]
Got it! But I don't think that's just a direnv thing. nvm sets the Node version per shell, so nvm use only applies to the current environment. Could you look into [$nvm_default_version](https://github.com/jorgebucaran/nvm.fish?tab=readme-ov-file#nvm_default_version)?
