### ISSUE TITLE
how to use the system version

### ISSUE THREAD

**Issue by robsonpeixoto** [fisherman/fin#23]
After choose a version using `fin` how can I roll back and start to use the system version?

**Comment by bucaran** [comment]
You can (1) remove the selected version with: `fin rm VERSION` or
(2) use `command node` or `command npm`.

**Comment by robsonpeixoto** [comment]
`fin rm VERSION` will uninstall or will remove the node from PATH ?

**Comment by bucaran** [comment]
It will remove it from the configuration so that both the node and npm shims can't find it, so you'll get the system version (if there is one).

Note that downloaded versions are always available in the cache too, so re-installing takes less than half a second.

**Comment by bucaran** [comment]
@robsonpeixoto Can we close? :)

**Comment by robsonpeixoto** [comment]
Yep @bucaran. But I prefer a command `fin system` to disable the shim.
