### ISSUE TITLE
v10.15.3 is not installed

### ISSUE THREAD

**Issue by posilya** [fisherman/fin#232]
**Playback steps:**

1. Exec `nvm install v10.15.3`

**Actual behavior:** The download does not start, an error pops up immediately.

**Expected behavior:** The download and installation of Node.js 10.15.3 will begin.

v10.15.2, interestingly, is loading.

**Output:**

```
realpath: пропущен операнд (translate, an operand is missing)
По команде «realpath --help» можно получить дополнительную информацию. (translate, You can get additional information by using the "realpath --help" command.)
fish: Unknown command: node
~/.config/fish/functions/nvm.fish (line 229): 
    command node --eval "
            ^~~^
in function '_nvm_node_info'
	called on line 1 of file ~/.config/fish/functions/nvm.fish
in command substitution
	called on line 140 of file ~/.config/fish/functions/nvm.fish
in function 'nvm' with arguments 'install v10.15.3'
Now using Node  (npm )
```

**Enviroment**:

```
fish: 3.7.1
OS: Linux 6.6.41-un-def-alt0.p11.1, ALT Starterkit 11 (Salvia)
```

**Comment by jorgebucaran** [comment]
Hey, do you think Fish realpath built-in might be missing or overwritten? It could be something in your setup, not a bug here.

**Comment by posilya** [comment]
Most likely, it was because I interrupted the download using ctrl+C, as the terminal was not proxying traffic. Thanks! 🤝
