### ISSUE TITLE
Error messages are misleading when attempting to switch to node versions < 0.10

### ISSUE THREAD

**Issue by derekcecillewis** [fisherman/fin#26]
When executing the command `fin 0.9`, or any version less than 0.10, the error message states the following: `fin: I couldn't find '0.9' in the version index.`

This, however, can be misleading as there are versions of node below 0.10 in the [version index where fin downloads its binaries](http://nodejs.org/dist/), even if fin does not support them. I believe a more appropriate error message would be the following: `fin: '0.9' is not a supported version. Please select version '0.10' or later.`, or if you want to keep fin in the first person: `fin: I do not support version '0.9'. Please select version '0.10' or later.` at least until fin supports those legacy versions.

**Comment by bucaran** [comment]
"I do not support..." sounds good to me!
