### ISSUE TITLE
How to use more the one node version in different terminal

### ISSUE THREAD

**Issue by robsonpeixoto** [fisherman/fin#27]
Sometime I need to use, for different projects, different node version at same time but in distinct shells.
But using fin I can not run two different projects with different node versions at the same time.

Are there plans to add support to it, like nvm do?

**Comment by bucaran** [comment]
For this you would use an .nvmrc file right?

**Comment by robsonpeixoto** [comment]
No necessary @bucaran. Some times I have 2 iterm tabs open: One using node 4.4.4 and another using node 6.1.0.

**Comment by bucaran** [comment]
But each project is in a different project right?

**Comment by bucaran** [comment]
@robsonpeixoto

**Comment by bucaran** [comment]
> Are there plans to add support to it, like nvm do?

What does nvm do?

**Comment by robsonpeixoto** [comment]
@bucaran I tested with `nvmrc (or .finrc or .node-version)` and it's work.

> What does nvm do?
First it do not use shim. And, to be honest, I do not like shim. I prefer to explicitly activate the node version that I would like to use. I do not like of the current design where the `~/.config/fin/bin` is always on the PATH with high priority. `Explicit is better than implicit.`

It set the current PATH variable with the path of node that you wanna use. It set another environment variables that is very useful to use on `fish_prompt.fish` to show if you are with a node version activated.

Talking about design, I really like it: https://github.com/terlar/fry. IMO the fin should be like it.

**Comment by bucaran** [comment]
>  I tested with nvmrc (or .finrc or .node-version) and it's work.

Great. 

> Talking about design, I really like it: https://github.com/terlar/fry. IMO the fin should be like it.

I don't know how fry works, so I can't comment on whether I like it or not. I looked quickly through the README, but couldn't easily figure out how to use it, so I gave up haha.

**Comment by bucaran** [comment]
@robsonpeixoto Thanks for un-starring the project :)

**Comment by jadengore** [comment]
@jbucaran A use case example would be when a project uses Nodemon and restarts itself when files are updated. If I am using different Node version in both shells, I have to run `fnm` in that shell to reset it to the correct version.

**Comment by robsonpeixoto** [comment]
I agree with @jadengore

**Comment by jbucaran** [comment]
@jadengore @robsonpeixoto I am open to this, but I don't have time to work on implementing this feature myself now. If anyone wants to take the challenge, I'd be happy to review your PR.

Cheers!
