### ISSUE TITLE
Landing page / site?

### ISSUE THREAD

**Issue by bucaran** [fisherman/fin#4]
I had some free time so I made a mockup for what I think would be a nice landing page for fin.

![site-fin](https://cloud.githubusercontent.com/assets/8317250/14521724/ce642a1c-0265-11e6-986d-92d164c01b6a.png)

## Logo variations

<p align=center>

<img src="https://cloud.githubusercontent.com/assets/8317250/14521726/d3ac526a-0265-11e6-8dc2-97dced2e5f6d.png"/>

<img src="https://cloud.githubusercontent.com/assets/8317250/14521728/d3d25762-0265-11e6-8aa3-e4baaa9c70a5.png"/>

<img src="https://cloud.githubusercontent.com/assets/8317250/14521729/d3e38f8c-0265-11e6-9790-bf95e320cd9b.png"/>

<img src="https://cloud.githubusercontent.com/assets/8317250/14521730/d3e5b406-0265-11e6-8bf2-14eab24e6e94.png"/>

</p>

**Comment by pickfire** [comment]
@bucaran, looks nice, how did you draw the mockup? I really hope to learn to create mockups.

And I like something like `$ curl...` but without the `$` being copied with some method like:
```css
cmd::before {
  content: "$";
  opacity: .5;
}
```
```html
<span id="cmd">curl -sLo ~/.config/fish/functions/fin.fish --create-dirs git.io/fin</span>
```

By the way, I can help to create icons for those words in the feature section.

**Comment by bucaran** [comment]
> By the way, I can help to create icons for those words in the feature section.

That would be a lot of icons, plus is hard work. If you have free time to spare give it a shot, but I am hoping to make this site even simpler than fisherman's site, just links and the wide pixel font.

**Comment by herrbischoff** [comment]
I totally dig the logo but not the main font, especially not the filled `O`. Also, black as a background color is not working for me. Could you share the PixelMator file so I can tinker with it later? Interesting choice, I usually use Sketch for mockups and designs, Affinity Designer for more complex icons.

Since web development is my main source of income, I can offer to work on the site and make it simple and responsive, SVG icons and all. I agree that what can be text should be text, even if I had to create a custom font for that purpose. ;)

**Comment by bucaran** [comment]
@herrbischoff Sweet! I appreciate all the help I can get with this. The filled `o` is because that's just how the font is, I don't dig that `o` either, but I am a sucker for old console / arcade game fonts.

Here is both the pixelmator source and the font.

https://github.com/bucaran/fin-site-mockup

**Comment by herrbischoff** [comment]
@bucaran: Nice, thank you. I'm playing around with it tonight and will send you suggestions as pull requests. Or should I upload screen shots here? Might be easier for others to review.

**Comment by bucaran** [comment]
Yeah, latter sounds more reasonable, that repo is just quick share this whole file with you kind of thing. I'll delete it after you have the file or after the design phase is over :smile:

**Comment by herrbischoff** [comment]
Interestingly, when opening in a font editor, the typeface does not contain a filled `O`:

<img width="500" alt="screen shot 2016-04-14 at 15 10 41" src="https://cloud.githubusercontent.com/assets/8957346/14529131/65eb36d6-0253-11e6-8742-a54e7529f8f6.png">

When using QuickLook, it does. However it looks like a glitch. Notice the fine lines separating the inner fill from the outline:

<img width="528" alt="screen shot 2016-04-14 at 15 10 55" src="https://cloud.githubusercontent.com/assets/8957346/14529143/79691034-0253-11e6-8ae3-885de3523672.png">

**Comment by bucaran** [comment]
Ha, I see, it must be a "glitch" then, because I can clearly see the white inline. I wouldn't know where to start in order to patch those o's.

**Comment by pickfire** [comment]
@bucaran, I can help to draw the svg icon out by hand.

**Comment by bucaran** [comment]
@pickfire That would be really helpful. This one is remarkably simpler than the original Fisherman logo. Before you do though, let's agree with @herrbischoff and @jethrokuan that this is the final logo.

**Comment by pickfire** [comment]
@bucaran, it's here, now I had gain some real world experience, thanks a lot, it can still be compressed but it won't worth it:
```svg
<svg xmlns="http://www.w3.org/2000/svg" height="50" width="50">
<path d="m17 14v15h3v-12h3v3h3v3h3v3h3v3h6v-15z"/>
</svg>
```
![2016-04-14-221220_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/14530981/05939284-028e-11e6-8ca4-7a47b4c7a21b.png)
![2016-04-14-221222_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/14530982/05c77766-028e-11e6-9f54-bd1e0eec4d80.png)

**Comment by bucaran** [comment]
Looking great man. What do you think about making the fin more obvious?

![fin-2](https://cloud.githubusercontent.com/assets/8317250/14531318/cdffa330-0297-11e6-9ee7-170b10523628.png)
![fin-3](https://cloud.githubusercontent.com/assets/8317250/14531317/cdfdec7a-0297-11e6-9919-9a77dca1a498.png)

**Comment by herrbischoff** [comment]
@pickfire: Good work! :+1:

**Comment by pickfire** [comment]
@bucaran Some simple update to make it shorter and nicer. The color in fin2 and aseprite looks nice, not sure which to choose:

![2016-04-15-151525_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/14556201/90433024-0329-11e6-8b89-7e82289faff3.png)
![2016-04-15-163643_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/14556202/90c1df0a-0329-11e6-8bdc-3b5df2b53ae1.png)
![2016-04-15-163718_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/14556204/90df7524-0329-11e6-8c3e-87b26e7e2fd4.png)

fin:
```svg
<svg xmlns="http://www.w3.org/2000/svg" height="11" width="29" fill="skyblue">
<path d="m3 3h7v1H4v1h3v1H4v2H3z"/>
<path d="m11 3v1h3v3h-3v1h7V7h-3v-3h3V3z"/>
<path d="m19 3v5h1V4h1v1h1v1h1v1h1v1h2V3z"/>
</svg>
```
fin1:
```svg
<svg xmlns="http://www.w3.org/2000/svg" height="11" width="29" fill="lightblue">
<path d="m3 3h7v1H4v1h3v1H4v2H3z"/>
<path d="m11 3v1h3v3h-3v1h7V7h-3v-3h3V3z"/>
<path d="m19 3v5h1V4h2v1h1v1h1v1h1v1h1V3z"/>
<path d="m21 4v1h1v1h1v1h1v1h1" fill="blue"/>
</svg>
```
fin2:
```svg
<svg xmlns="http://www.w3.org/2000/svg" height="11" width="29" fill="#4bf">
<path d="m3 3h7v1H4v1h3v1H4v2H3"/>
<path d="m11 3v1h3v3h-3v1h7V7h-3v-3h3V3"/>
<path d="m21 4v1h1v1h1v1h1v1h1V4" fill="#bdf"/>
<path d="m19 3v5h1V4h2v1h1v1h1v1h1v1h1V3"/>
</svg>
```
fin3:
```svg
<svg xmlns="http://www.w3.org/2000/svg" height="11" width="29" fill="skyblue">
<path d="m3 3h7v1H4v1h3v1H4v2H3z"/>
<path d="m11 3v1h3v3h-3v1h7V7h-3v-3h3V3z"/>
<path d="m21 4l4 4V4" fill="#adf"/>
<path d="m19 3v5h1V4h2v1h1v1h1v1h1v1h1V3z"/>
</svg>
```
In case you want to set the background color, you can do it with css:
```css
logo {
  background-color: #fff;
}
```
I think it's time to compress these now as it is over 200 byte.

**Comment by jethrokuan** [comment]
really nice @pickfire :+1:

**Comment by herrbischoff** [comment]
@bucaran: I could fix the font — it's a TrueType format issue. However:

<img width="725" alt="screen shot 2016-04-15 at 17 48 39" src="https://cloud.githubusercontent.com/assets/8957346/14567076/a426d484-0332-11e6-8024-a7b7724a7d6e.png">

The font license does not allow for anything else than personal use. Use as a web font or even just usage on a public site is therefore not allowed.

**Comment by pickfire** [comment]
@bucaran, I can help to implement the site too but I currently have no idea how to set the fonts to the one you use.

**Comment by bucaran** [comment]
@pickfire Well, as explained by @herrbischoff, we shouldn't be using the font for the website because it's copyrighted.

**Comment by pickfire** [comment]
@bucaran, maybe we could make ours that look almost the same. But with a different license. Can we?

By the way, I suggest to use `light weight` instead of `light`.

**Comment by bucaran** [comment]
@pickfire Why not

@herrbischoff How do I make a font? Would you mind demystifying this process for us?

**Comment by lordlycastle** [comment]
@bucaran I wouldn't recommend making a new font by yourself, it's gruelling. However, I don't know how difficult a pixel font would be. Better just find other font that looks similar. If you still wanna have a look around, I used [GlyphsApp](https://glyphsapp.com) to edit one of the fonts.

Personally I like the logo where fin is more obvious, your first one, or @pickfire's bottom left one.

**Comment by bucaran** [comment]
@lordlycastle That app looks terrific and it has a free trial too. I think creating a font for fin would be a lot of work that I rather should invest on fin itself.

I wonder if just creating svg or png version of the written features is no-good?

**Comment by herrbischoff** [comment]
I don't think that creating a font yourself for the sole purpose of a landing page would be a reasonable use of time. Creating a font that is not just a hastily slapped together collection of inconsistent glyphs takes *a lot* of time and care. The Glyphs software is great, but keep in mind that it's a 250 € commercial app — and you will take longer than 30 days the trial runs.

To get an idea what's involved in creating your own typeface, take a look at this book: http://designwithfontforge.com/. FontForge itself works unfortunately terrible on Mac OS X (needs X11, non-retina, slow, clunky, 100% custom interface) but it's free.

As for @pickfire's idea

> maybe we could make ours that look almost the same. But with a different license. Can we?

No, we cannot. That would be a head-on rip-off. You could create your own pixel alphabet though which I would be happy to turn into a font. As long as the amount of glyphs cover only the basics we need.

**Comment by herrbischoff** [comment]
> I wonder if just creating svg or png version of the written features is no-good?

If you care *at all* about search engines being able to index the site, this is no way. Imagine PNG or SVG files a big piles of unknown data, Google and others don't know how to interpret. The meaning of a page without readable text is mainly unknown to Google.

**Comment by bucaran** [comment]
@herrbischoff Yep, you are right, this would be a terrible idea. Maybe I should find a way to contact Sizenko to ask for permission. Who, knows

**Comment by herrbischoff** [comment]
@bucaran: If you're sold on the font, here's the email address I could dig out from [the site](http://www.styleseven.com):
ms-7@styleseven.com

Good luck! :)

**Comment by bucaran** [comment]
Thanks, sent an email asking for him first, let's see what comes out of this. I am hopeful.

**Comment by herrbischoff** [comment]
This should be interesting. The ideal result would be permission to use it as a web font and slightly modify it for our uses along the way.

**Comment by bucaran** [comment]
tbh I'd be happy and awfully grateful with just usage.

**Comment by herrbischoff** [comment]
Don't forget: it's NOT a web font yet and none is provided. Plus, there's the issue with the filled `O`. Using it as a web font means converting it. Fixing the TrueType issue as well as making a web font out of it in effect mean modifying the original.

**Comment by bucaran** [comment]
Absolutely, if we can't get permission to play with the font, then we can change the design to something else or put the website project on hold unless a new design is presented.

**Comment by bucaran** [comment]
@fishery/all 

Sizenko's reply:

<img width="769" alt="screen shot 2016-04-17 at 5 06 59 pm" src="https://cloud.githubusercontent.com/assets/8317250/14585809/93fa70e2-04be-11e6-9b2a-f326eeec9263.png">

**Comment by sotayamashita** [comment]
@bucaran  Wow It's looks very old game but I like it. If you need a help to create it, please let me know.

**Comment by bucaran** [comment]
@sotayamashita Thanks! the more help the better. Now that we have green light from Sizenko, we should go back to @herrbischoff comment here: https://github.com/fishery/fin/issues/4#issuecomment-209931835

**Comment by herrbischoff** [comment]
Alright, I'll get right on it to make the corrected version and the web font! :)

**Comment by herrbischoff** [comment]
Here you go, it's an OpenType version containing a TrueType font:
[WidePixel-7-Regular.zip](https://github.com/fishery/fin/files/222700/WidePixel-7-Regular.zip)

**Comment by herrbischoff** [comment]
Looks like I'm going to to start working on the site, @bucaran! :D Let me set up a small project so we can jointly polish it. As soon as I have the base in place, I will open a repository and announce it here. We can then move the discussion of the site here. Sounds good?

**Comment by bucaran** [comment]
@herrbischoff Sounds perfect. Would you like me to set up a private project for us? I would appreciate if we can also invite @sotayamashita and @pickfire to the repo. 

@jethrokuan You in too?

**Comment by herrbischoff** [comment]
@bucaran: Private repo sounds good. No need for everyone to see work in progress... ;) Invite away, more eyes see more things.

**Comment by bucaran** [comment]
Done. It has to be bucaran/fin.github.io, since that's all I can do. Invited @sotayamashita too.

If anyone else wants to join just ping me here.

**Comment by pickfire** [comment]
@bucaran, @herrbischoff I have did some part of it. Too bad I told you guys too late:

![2016-04-18-064414_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/14590582/0407726e-0531-11e6-9a76-35edd61471d2.png)
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Fin - light fish's plugin manager</title>
    <style>
* { margin: 0; padding: 0; }
body {
  margin: 0 auto;
  font: 200% monospace;
  color: #fdd838;
}
body:not(#get) {
  text-align: center;
  max-width: 25em;
  background-color: #000;
}
a { text-decoration: none; color: #fd0; }
a, p { text-transform: uppercase; }
#head { padding: 1ex; margin: 1em; }
#get {
  display: block;
  margin-bottom: 40%;
}
#get p {
  margin: 1em;
  padding: 1em;
  font-size: 150%;
  color: #000;
  background-color: #fdd838;
}
#get code {
  position: absolute; left: 0; right: 0;
  margin: 2em 0; padding: 2ex;
  color: #616161; background-color: #212121;
}
#pros p { word-spacing: 9999em; margin: 1em 0; }
#pros p:nth-child(even) { color: #424242; }
#pros p:nth-child(odd) { color: #fd0; }
.l { float: left; }
.r { float: right; }
footer * { color: #9e9e9e; margin-top: 1em; padding: 0 5px; }
    </style>
  </head>
  <body>
    <div id="head">
      <span class="l">
        <a href="#">Demo</a>
      </span>
      <span class="r">
        <a href="https://github.com/fishery/fin">Github</a>
      </span>
    </div>
    <svg height="20em" width="10em" viewBox="0 0 23 5" fill="#4bf">
      <path d="m0 0h7v1H1v1h3v1H1v2H0"/>
      <path d="m8 0v1h3v3h-3v1h7V4h-3v-3h3V0"/>
      <path d="m18 1v1h1v1h1v1h1v1h1V1" fill="#bdf"/>
      <path d="m16 0v5h1V1h2v1h1v1h1v1h1v1h1V0"/>
    </svg>
    <div id="get">
      <p>Get</p>
      <code>curl -#Lo ~/.config/fish/functions/fin.fish git.io/fin</code>
    </div>
    <div id="pros">
      <p>One File</p>
      <p>Parallel Downloads</p>
      <p>No Deps</p>
      <p>All Compact</p>
      <p>Minimal</p>
      <p>Frame Work Neutral</p>
      <p>Light Weight</p>
      <p>Non Invasive</p>
    </div>
    <footer>
      <svg height="20" width="26" viewBox="0 0 7 5" fill="#9e9e9e">
        <path d="m0 0v5h1V1h1v1h1v1h1v1h1v1h2V0"/>
      </svg>
      <a href="#">Releases</a>
      <a href="#">FAQ</a>
    </footer>
  </body>
</html>
```
There are still some things needed to be done.

**Comment by herrbischoff** [comment]
@pickfire: Please wait a little until I have set up and uploaded the base of the site. We're also going to use Jade (now called pug) and Stylus for building the site.

There are some no-go's in your HTML structure and some rather weird CSS. Let's talk about all of this when the base structure is done.

**Comment by jethrokuan** [comment]
@bucaran sure. It's interesting to see what everyone's go-to is when building a static site.

**Comment by sotayamashita** [comment]
@herrbischoff Which repository are you creating site ?

**Comment by bucaran** [comment]
@jethrokuan @pickfire Thanks! I am inviting you two to the private repo.

**Comment by dalln1** [comment]
@bucaran I would also like to join. I am here to learn.

**Comment by pickfire** [comment]
@dalln1 Same here, I want to learn too. I hope to learn to draw mockup and do monkey faces. I hope you can tell me more about joining other's project to learn.

@herrbischoff Yeah it seems a bit weird as it's just my prototype. I hope to learn to create a site as I have low experience with web development.

**Comment by bucaran** [comment]
You have an interesting homepage @pickfire 😄

**Comment by pickfire** [comment]
@bucaran, I copied it from suckless design and papercolor theme and generate it using my own generator that I had created using `mksh`.

**Comment by bucaran** [comment]
@pickfire Haha it's old school, but I like it.

**Comment by pickfire** [comment]
@herrbischoff Is it readied yet? :pray:

**Comment by bucaran** [comment]
@pickfire Haha, there's no hurry.

**Comment by bucaran** [comment]
This is relevant:

https://github.com/fisherman/fisherman/issues/204#issuecomment-212749114

**Comment by herrbischoff** [comment]
Wow, this is kind of unexpected. Does this mean that the site is off the table? Fisherman already has one.

**Comment by jethrokuan** [comment]
@herrbischoff now that they've merged, fisherman is looking to revamp the site. there's a discussion at https://github.com/fisherman/fisherman/issues/212

**Comment by bucaran** [comment]
@herrbischoff fin is finalized, but it lives in fisherman :)

wrt to the site, we could do whatever we want / you guys are up to. Reusing some of these assets is fine too, continuing the existing fisherman theme okay too.

**Comment by bucaran** [comment]
Closing in favor of fisherman/fisherman#212.
