### ISSUE TITLE
Installation from github.com does not work

### ISSUE THREAD

**Issue by johnfraney** [fisherman/fin#6]
I'm getting an error when trying to install a plugin via GitHub in my `fishfile`:

```
john@arch ~/.config> fin
fin: Fetch error github.com/fisherman/metro
```

Fishfile:
```fish
github.com/fisherman/metro
```

Adding the protocol in the `fishfile` works as expected (e.g., `https://github.com/fisherman/metro`)

**Comment by brj** [comment]
@johnfraney Observed and fixed.
