### ISSUE TITLE
Remove Dependencies

### ISSUE THREAD

**Issue by ndalliard** [fisherman/fin#6]
When I installed for example [Simple](https://github.com/fishery/simple), fin installed some dependencies. When I `fin rm simple`, the dependencies stay and I've to remove them from hand.

**Comment by bucaran** [comment]
@dalln1 Yeah, I've been thinking about this too.

Removing `simple` should remove its dependencies, but only if they are not currently being used by other plugin, correct?

**Comment by dalln1** [comment]
What if the user installed them himself and maybe uses them for something else? Is that a possible scenario? Would make it a little bit harder to realise I think.

**Comment by bucaran** [comment]
Imagine someone installs `segment`, to help them prototype a new prompt/theme they are working on.

While they are at that, they also install `stark` or `superman`, for whatever reason, because they like it, or because they want to see `segment` in action.

Later they decide they don't want either of those and `fin rm stark superman`. By definition, this should remove `segment`, since these two libraries use it, but then that's not what the user was expecting.

**Comment by dalln1** [comment]
Perfectly said. And the solution with the `!` is awesome!

**Comment by bucaran** [comment]
@jethrokuan @herrbischoff Do you see any potential issues with this proposal?

**Comment by lordlycastle** [comment]
Sounds like a good plan. One thing to consider, we'd also need a way to mark installed plugins with `!`. Following on you example, say user installs `stark` and decides on creating his own plugin which requires `segment`, so uninstalling `stark` would break his plugin. 

@bucaran What happen's when you try to uninstall a plugin which is a dependency? Does it just give error and exit?

**Comment by pickfire** [comment]
@bucaran, I seem some issue having unable to really uninstall an application.

When I update after uninstalling superman, superman is still in one of my update. Weird bug, I can't reproduce it now.

**Comment by bucaran** [comment]
@pickfire I don't understand what you are saying 😕

**Comment by jethrokuan** [comment]
I can think of an edge scenario here.

1. Someone installs a theme, `superman` for example, which requires `segment`
2. Said person now wants to use segment to develop his own theme.

What should he do? `fin install segment` to add a "!"? This should, like most things, be an implementation detail and should not require user knowledge.

tbh I don't think there'll ever be a perfect solution.

**Comment by bucaran** [comment]
The problem is we are using a flat tree. And we are using a flat tree, not because it's fast. Well, we are, but the main reason is, fish does not have private scope for functions.
