### ISSUE TITLE
Plugins in .config/fish/conf.d/ do not load

### ISSUE THREAD

**Issue by andrewrynhard** [fisherman/fin#7]
I noticed that plugins located here are not loaded. Do I need to update my fish or is this an issue with fin?

**Comment by andrewrynhard** [comment]
I installed fish from git and the plugins now load

**Comment by bucaran** [comment]
Hi @andrewrynhard, this is addressed in the FAQ.

> fin was built for the latest fish, but at least 2.2.0 is required. If you can't upgrade your build, append the following code to your ~/.config/fish/config.fish for snippet support.
```fish
for file in ~/.config/fish/conf.d/*.fish
    source $file
end
```

**Comment by bucaran** [comment]
Hi @andrewrynhard, this is addressed in the FAQ.

> fin was built for the latest fish, but at least 2.2.0 is required. If you can't upgrade your build, append the following code to your ~/.config/fish/config.fish for snippet support.
```fish
for file in ~/.config/fish/conf.d/*.fish
    source $file
end
```

However, I would recommend using `conf.d` directly in your plugins and avoiding `init.fish` as that feature is only to support oh-my-fish and may be removed in the future.
