### ISSUE TITLE
Ideas for the future of fin

### ISSUE THREAD

**Issue by bucaran** [fisherman/fin#9]
@fisherman/all 

So fisherman 2.0 was the "end" of fin as we knew it, but that does not mean it must be gone gone. We still can do something with this repository and the name `fin`.

If you have any ideas, please share them!

I know @pickfire will have some interesting ideas.

**Comment by pickfire** [comment]
@bucaran Most of my ideas is interesting (non-serious) name change and setting all the things in a file and just add some nice comments in it.

**Comment by bucaran** [comment]
@pickfire What's the idea?

**Comment by sotayamashita** [comment]
vandle file like package.json. I mean it include plugins name and version.

**Comment by bucaran** [comment]
fin is now a node version manager similar to https://github.com/wbyoung/avn, https://github.com/creationix/nvm and https://github.com/tj/n.

Long live fin.
